version: "3"
services:
    nginx:
        image: nginx:1.13
        ports:
            - 80:80
        volumes:
            - .:/usr/share/nginx
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - server
        links:
            - php
    
    php:
        image: php:7.1.6-fpm
        expose:
            - 9000
        volumes:
            - .:/usr/share/nginx
        networks:
            - database
            - server
        links:
            - mysql
    
    mysql:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - database
        ports:
            - "6666:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

volumes:
    db_data:
networks:
    server:
    database: